config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :trees
  root 'home#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tree.rb
class Tree < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :set_tree, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit update destroy ]
  # GET /trees or /trees.json
  def index
    @trees = Tree.all
  end

  # GET /trees/1 or /trees/1.json
  def show
  end

  # GET /trees/new
  def new
    @tree = Tree.new
  end

  # GET /trees/1/edit
  def edit
  end

  # POST /trees or /trees.json
  def create
    @tree = Tree.new(tree_params)

    respond_to do |format|
      if @tree.save
        format.html { redirect_to tree_url(@tree), notice: "Tree was successfully created." }
        format.json { render :show, status: :created, location: @tree }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trees/1 or /trees/1.json
  def update
    respond_to do |format|
      if @tree.update(tree_params)
        format.html { redirect_to tree_url(@tree), notice: "Tree was successfully updated." }
        format.json { render :show, status: :ok, location: @tree }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trees/1 or /trees/1.json
  def destroy
    @tree.destroy!

    respond_to do |format|
      format.html { redirect_to trees_url, notice: "Tree was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree
      @tree = Tree.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tree_params
      params.require(:tree).permit(:name, :x, :instagram, :youtube, :user_id, :style)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/home/index.html.erb
<%= link_to "New Tree", new_tree_path %><br>

app/views/layouts/_navbar.html.erb
<%= image_tag ("tree.png"), style: "width: 100px; " %>
<%= link_to "Sign up", new_user_registration_path %>

<%= link_to "log in", new_user_session_path %>

<% if user_signed_in? %>
<%= link_to "Sign out", destroy_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LinktreeClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= render "layouts/navbar"%>
    <%= yield %>
  </body>
</html>

app/views/trees/_form.html.erb
<%= form_with(model: tree) do |form| %>
  <% if tree.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tree.errors.count, "error") %> prohibited this tree from being saved:</h2>

      <ul>
        <% tree.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :x, style: "display: block" %>
    <%= form.text_field :x %>
  </div>

  <div>
    <%= form.label :instagram, style: "display: block" %>
    <%= form.text_field :instagram %>
  </div>

  <div>
    <%= form.label :yotube, style: "display: block" %>
    <%= form.text_field :yotube %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :style, style: "display: block" %>
    <%= form.text_field :style %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trees/_tree.html.erb
<div id="<%= dom_id tree %>">
  <p>
    <strong>Name:</strong>
    <%= tree.name %>
  </p>

  <p>
    <strong>X:</strong>
    <%= tree.x %>
  </p>

  <p>
    <strong>Instagram:</strong>
    <%= tree.instagram %>
  </p>

  <p>
    <strong>Yotube:</strong>
    <%= tree.youtube %>
  </p>

  <p>
    <strong>User:</strong>
    <%= tree.user_id %>
  </p>

  <p>
    <strong>Style:</strong>
    <%= tree.style %>
  </p>

</div>

app/views/trees/edit.html.erb
<h1>Editing tree</h1>

<%= render "form", tree: @tree %>

<br>

<div>
  <%= link_to "Show this tree", @tree %> |
  <%= link_to "Back to trees", trees_path %>
</div>

app/views/trees/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Trees</h1>

<div id="trees">
  <% @trees.each do |tree| %>
    <%= render tree %>
    <p>
      <%= link_to "Show this tree", tree %>
    </p>
  <% end %>
</div>

<%= link_to "New tree", new_tree_path %>

app/views/trees/new.html.erb
<h1>New tree</h1>

<%= render "form", tree: @tree %>

<br>

<div>
  <%= link_to "Back to trees", trees_path %>
</div>

app/views/trees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tree %>

<div>
  <%= link_to "Edit this tree", edit_tree_path(@tree) %> |
  <%= link_to "Back to trees", trees_path %>

  <%= button_to "Destroy this tree", @tree, method: :delete %>
</div>